services:
  - type: web
    name: backend
    env: python
    plan: starter
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.wsgi:application
    autoDeploy: true